### ISSUE TITLE
Issue Stop Great Race #16

### ISSUE THREAD

**Issue by e-sau** [crowdwiz-biz/crowdwiz-core#17]
Добрый день. После последнего обновления https://github.com/crowdwiz-biz/crowdwiz-core/pull/1  и https://github.com/crowdwiz-biz/crowdwiz-core/pull/16/ нода в докере перестала принимать блоки после 2023-04-03T17:59:55. 
В чем может быть причина?
Спасибо.

**Comment by zerolabnet** [comment]
Подтверждаю, прописанные seeds node's не отдают новые блоки.

Одна из seeds node точно доступна:
nc -zv 194.67.71.43 1776
nc: connectx to 194.67.71.43 port 1776 (tcp) failed: Operation timed out
nc -zv 185.193.125.52 1776
Connection to 185.193.125.52 port 1776 [tcp/femis] succeeded!
nc -zv 68.183.242.188 1776
nc: connectx to 68.183.242.188 port 1776 (tcp) failed: Connection refused

**Comment by tprvx** [comment]
Доброго времени суток!

**Comment by tprvx** [comment]
Если нода не видит другие ноды, и не получает от них блоки, застряла к примеру после строки chain-id, можно прописать в файле config.ini seed-node = 94.228.121.111:1776, это должно решить проблему. Те ноды видимо еще не обновились после обновления.

>

**Comment by e-sau** [comment]
@tprvx  спасибо за ответ
в адресе нет ошибки 94.228.121.1111? последние 1111 (4 единицы) смущают

**Comment by tprvx** [comment]
> @tprvx спасибо за ответ в адресе нет ошибки 94.228.121.1111? последние 1111 (4 единицы) смущают

Да, конечно, исправил уже, опечатка)

**Comment by e-sau** [comment]
Добрый вечер.
Нода запустилась, но теперь последний блок - 24501605 (2023-04-05T05:59:55).
И насколько вижу, на публичных нодах тоже самое. Будет снова обновление?

**Comment by tprvx** [comment]
Добрый вечер! Да, скоро будет обновление, сообщим думаю в чатах и тут новый коммит будет, как всё будет готово

**Comment by crowdwiz-biz** [comment]
> Добрый вечер. Нода запустилась, но теперь последний блок - 24501605 (2023-04-05T05:59:55). И насколько вижу, на публичных нодах тоже самое. Будет снова обновление?

Обновление готово, кто имеет любые свои ноды, нужно залить новый код и выполнить make. Затем обязательно запустить ноду с параметром --replay-blockchain

**Comment by crowdwiz-biz** [comment]
.
