### ISSUE TITLE
Разделились цепочки

### ISSUE THREAD

**Issue by e-sau** [crowdwiz-biz/crowdwiz-core#21]
Добрый день. Сегодня часть нод "пошла своим путем". Подскажите пожалуйста, как их снова синхронизировать? Необходимо сносить БД или есть более удобный путь?

**Comment by crowdwiz-biz** [comment]
Добрый день! Прошу прощения что вовремя не заметили вопрос, из за временной сетевой недоступности нескольких витнесов, когда работы были на крупном интернет шлюзе провайдера, несколько витнесов оказались в изолированном сегменте сети и форк произошел. Перейти на "истинную" сеть можно только удалив блоки из форка, поэтому лучше удалить блоки и снова скачать актуальную версию блокчейна. Более удобного пути нет при таком случае.
